# Models records
base_bw:
  hidden_dim: 16
  nb_hidden_layers: 3
  latent_dim: 16
  nb_channels: 1
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.
  inner_activation: tanh
  inner_architecture_key: base
base_rbg:
  hidden_dim: 32
  nb_hidden_layers: 4
  latent_dim: 32
  nb_channels: 3
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.5
  inner_activation: tanh
  inner_architecture_key: base
residual_01:
  hidden_dim: 32
  nb_hidden_layers: 4
  latent_dim: 16
  nb_channels: 1
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.0
  inner_activation: tanh
  inner_architecture_key: softplus
rgb_bland:
  hidden_dim: 32
  nb_hidden_layers: 8
  latent_dim: 16
  nb_channels: 3
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.0
  inner_activation: tanh
  inner_architecture_key: base
rgb_test:
  hidden_dim: 16
  nb_hidden_layers: 5
  latent_dim: 16
  nb_channels: 3
  scale_factor: 1.
  kernel_init_mean: 0.
  kernel_init_stddev: 1.0
  inner_activation: tanh
  inner_architecture_key: base
# Data transformation records
test_config:
  scale: 1.0
  translation: 0.
  rotation: 45.
  scale_speed: 0.
  translation_speed: 0.
  rotation_speed: 10
  extra_fun: cos_sin